name: Deploy to server
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copying new files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "*"
          target: ${{ secrets.TARGET_FOLDER }}
          rm: true
      - name: Reloading app
        uses: fifsky/ssh-action@master
        with:
          command: source ~/.bashrc && cd ${{ secrets.TARGET_FOLDER }} && npm install && echo '{"port":7777}' > config.json && pm2 restart YouDownloader
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}