name: Deploy to server
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copying new files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "*"
          target: ${{ secrets.TARGET_FOLDER }}
          rm: true
      - name: Reloading app
        uses: fifsky/ssh-action@master
        with:
          command: bash -c "cd ${{ secrets.TARGET_FOLDER }} && ~/.nvm/versions/node/v14.16.0/bin/npm install && pm2 restart YouDownloader"
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}